### ISSUE TITLE
Comparison with Bonsai?

### ISSUE THREAD

**Issue by feelingsonice** [hyranno/bevior_tree#34]
There seems to be another, general purpose behavior tree implementation named [bonsai](https://github.com/Sollimann/bonsai). While I haven't used neither this nor bonsai but wondering if you have any advice comparing the two? Thanks in advance :)

**Comment by hyranno** [comment]
Honestly, I don't know bonsai well. So expect this answer is not so trustworthy.

Using bonsai :
* Bonsai is for general purpose. This will be relatively robust to change game engine. Though you will need some code for convenient use in bevy.
* Bonsai has closed set of `Behavior` (matches to `Node` in bevior_tree). Writing complex flow like "sequentially execute actions in random order" will be tricky.

Using bevior_tree :
* `Node` is open to new implements, so if you need something special, you can write your own.
* I don't assure you active maintenance nor stable api.

Style of how to write `Action`/`TaskBridge` is largely different.
See examples of both.

I heard some people uses bonsai on Bevy.
They will be on ai channel in Bevy discord, or bonsai repository.

**Comment by hyranno** [comment]
v0.5 release is coming for bevy 0.13.
Some other ideas exists, but not planned for now.
