### ISSUE TITLE
insert_while_running should accept scheduler.

### ISSUE THREAD

**Issue by seivan** [hyranno/bevior_tree#43]
Most of the logic that a Behaviour Tree does should fall under a fixed time step.
Allow defining the scheduler for inserting/removing components for tasks.

**Comment by hyranno** [comment]
[BehaviorTreePlugin::in_schedule](https://docs.rs/bevior_tree/latest/bevior_tree/struct.BehaviorTreePlugin.html#method.in_schedule) is not enough?

**Comment by seivan** [comment]
It is. My bad.
